name: CI-CD
on: push
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CICD"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - name: Lint
        run: npm run lint
      - name: Build Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: ls
        run: ls -ltrha
      - name: Zip
        run: tar czvf build.gz build/
      - name: Verify
        run: file build.gz
      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./build.gz"
          target: "/home/iranperson"
      - name: Remote gunzip
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: tar xvf build.gz && rm build.gz
      - name: Verify
        run: ls -ltrh
